# This is a wakatime workflow
# https://wakatime.com/welcome
name: Waka Readme

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"
    # Runs every 2 hours
    #- cron: "0 */2 * * *"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update-readme"
  update-readme:
    name: WakaReadme DevMetrics
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # athul/waka-readme@master # this action name
      - uses: anmol098/waka-readme-stats@master 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: zh
          SHOW_TITLE: true
          COMMIT_MESSAGE: Update Wakapi stats
          BLOCKS: "⬜🟨🟩"
          #TIME_RANGE: last_30_days
          SHOW_LINES_OF_CODE: True
          SHOW_LOC_CHART: False
          SHOW_SHORT_INFO: False
